backend:
  name: git-gateway

media_folder: "img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "clients"
    label: "Clients"
    folder: "content/_clients"
    create: true
    slug: "{{index}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "people"
    label: "Team Members"
    folder: "content/_people"
    create: true
    slug: "{{index}}-{{slug}}"
    fields:
      - {label: "Full Name", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - label: Social Accounts
        name: social
        widget: list
        fields:
          - label: Name
            name: title
            widget: select
            options:
              - { label: "Twitter", value: "twitter" }
              - { label: "Facebook", value: "facebook" }
              - { label: "Stack Overflow", value: "stack-overflow" }
              - { label: "LinkedIn", value: "linkedin" }
              - { label: "Google Plus", value: "google-plus" }
          - {label: "Url", name: "url", widget:"string"}
