backend:
  name: git-gateway

media_folder: "img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "clients"
    label: "Clients"
    folder: "content/_clients"
    create: true
    slug: "{{index}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
